import React, {Component, Fragment} from "react"
import YouTubeComp from "../../../component/YouTubeComp/YouTubeComp"
import "./Youtube.css"
class Youtube extends Component {
	render() {
		return (
			<Fragment>
				<p className="section-title">Youtube</p>
				<hr />
				{/* <YouTubeComp
                    time="7.30"
                    title="cara menjadi youtuber"
                    desc="desc 1" /> */}
				<YouTubeComp time="8.30" title="menjadi youtuber" desc="desc 2" />
				<YouTubeComp time="9.30" title="cara menjadi programmer" desc="desc 3" />
				<YouTubeComp time="3.30" title="cara menjadi developer" desc="desc 4" />
				<YouTubeComp time="4.30" title="javascript lanjutan" desc="desc 5" />
				<YouTubeComp />
				<p>
					Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam aliquid minima, quisquam sit omnis quae, delectus similique praesentium, necessitatibus quas autem debitis veritatis placeat assumenda neque corporis! Consequuntur harum accusantium non voluptatem, veniam exercitationem voluptates aspernatur asperiores quasi, laborum fugit nihil est laudantium dicta aliquid corrupti iusto officiis. Voluptatibus aspernatur impedit harum iusto iure ex debitis cumque fugiat iste, reiciendis minus molestiae commodi nulla ullam officia maxime molestias, in omnis quaerat! Repudiandae officiis aut delectus suscipit necessitatibus temporibus nihil sunt nam magnam porro amet exercitationem cupiditate nesciunt, tempora inventore velit dolor nostrum. Sequi, quos dolores? Consequatur labore assumenda, veniam earum eius nostrum nihil quasi dicta ratione cupiditate eaque qui esse doloribus et quibusdam ullam, officia temporibus, necessitatibus adipisci reprehenderit hic! Veniam numquam quos esse
					eos itaque dicta a odio cumque facere architecto ipsum temporibus at alias laborum perferendis nam sunt dignissimos odit repudiandae blanditiis, deleniti quia enim suscipit. Aut nulla pariatur quo reprehenderit, aspernatur itaque iste iusto officiis magnam, adipisci error, quod inventore voluptatem? Veniam quos quisquam vero perspiciatis commodi dolorum quis accusantium eveniet officiis dolor excepturi, a soluta autem enim necessitatibus numquam sapiente aut ipsam saepe illum, at sequi! Quia doloribus aspernatur quibusdam, repellendus cupiditate fugiat vitae odit, corporis iste error, fugit explicabo velit? Quae eum deleniti debitis nulla? Maiores ipsum neque sapiente sit corporis dolores necessitatibus optio quidem nesciunt. Vero natus corporis voluptatibus veritatis eaque ullam qui dignissimos doloremque cumque corrupti, eos laudantium aperiam placeat quo a. Quae, totam asperiores mollitia dicta animi placeat expedita fuga ab! Commodi corporis ipsam harum nisi labore
					quibusdam voluptates, non libero esse qui sunt ex aliquam, voluptatum natus dolore quam nulla. Ullam sed placeat reiciendis qui possimus deleniti labore esse a laboriosam reprehenderit expedita facilis, vel laborum tempore impedit voluptatibus mollitia? Non ut at laudantium eum numquam ab modi architecto error iste deserunt incidunt, impedit qui labore blanditiis quo nulla illum quas aut culpa ad ipsa. Soluta fugit facere aliquid, deserunt pariatur, tempore voluptatem quaerat officia perspiciatis animi reiciendis cum officiis mollitia totam quo neque eos minima voluptas magnam et quasi ullam saepe numquam ipsam. Consectetur quod error iste doloremque libero veniam delectus accusantium maiores culpa, vitae quam deserunt ducimus optio iure ea illum velit cupiditate minus, neque quas accusamus, eum iusto. Quo sit quaerat, minus dicta nesciunt deserunt quibusdam nihil et consequuntur? Odit soluta ipsa dolores rerum ex reprehenderit quam nisi laboriosam autem suscipit perferendis
					ipsum voluptatum dolor et, aut reiciendis, excepturi voluptatibus. Quo beatae nobis accusamus repudiandae amet nostrum voluptate tempora eveniet exercitationem nesciunt similique sint, numquam expedita, voluptatibus ipsam, possimus quas. Incidunt nihil eos, est ullam ratione quidem expedita reiciendis consequuntur nobis eveniet excepturi qui temporibus ipsam amet dolores veritatis reprehenderit vel id nemo natus dignissimos dicta. Enim aliquid nesciunt facilis exercitationem natus ab esse a, nulla ratione officiis error quibusdam sed optio inventore reiciendis labore commodi illo tenetur dolore dolores voluptatum similique molestiae dignissimos. Sed explicabo eum quos aperiam accusamus unde doloremque amet, id facere animi tempore incidunt voluptates a perspiciatis in dolore porro aliquam nemo esse molestias culpa. Dolorum quibusdam nihil sunt expedita facere necessitatibus molestias quidem nostrum, blanditiis, quisquam omnis amet itaque unde deleniti nemo nesciunt ratione,
					ipsum debitis deserunt ad voluptas cumque. Repellat numquam minus minima beatae nisi animi id! Ad modi at architecto quis nesciunt pariatur. Voluptas debitis minus iure! Vitae quis quidem quia error voluptas voluptates dicta laborum facere. Necessitatibus impedit quam ex voluptate iure magnam, non quisquam sunt dolorem rerum consequatur cupiditate ab possimus at aliquam fugit facilis nostrum pariatur enim earum totam accusamus nesciunt. Quos possimus a accusantium blanditiis debitis? Sit, dignissimos? Ipsa, fugit obcaecati, quo tenetur dolores rem repudiandae expedita accusamus iure nobis fugiat atque, labore ea. Facere, voluptatum eius et ab iusto quae laboriosam nihil hic molestias ex fuga? A quas repellendus recusandae excepturi labore quo nisi sapiente sequi minima eveniet? Officia expedita labore eum nam fugit quasi itaque quibusdam ipsam blanditiis dolorem, ipsum magni voluptatum cum sed facere neque adipisci minima quis? Quae laboriosam minima rerum sed asperiores, rem
					eos animi omnis consequuntur qui delectus modi molestias veritatis? Eum, vitae expedita consectetur doloribus a quia quisquam corrupti tempore velit quas, omnis blanditiis nihil. Dicta consectetur tenetur illum unde, consequuntur, veniam distinctio culpa impedit numquam aliquid suscipit ducimus modi neque. Nobis ad, nihil accusantium sapiente ea officia nesciunt odit vitae earum voluptatem quos optio suscipit reprehenderit amet provident nulla, vel nostrum! Reprehenderit expedita possimus harum aliquam ex minima nostrum, dolorem repellat provident quaerat natus iste recusandae corrupti officiis consequatur, id eaque sed rem error debitis laborum! Atque praesentium excepturi consequuntur quisquam optio officiis unde, ex rem reprehenderit necessitatibus nostrum nulla voluptatem, cupiditate architecto inventore quaerat alias id voluptatum doloribus ratione facere perspiciatis assumenda. Nostrum commodi asperiores reprehenderit non ipsum sed recusandae expedita distinctio numquam
					quaerat. Iste, consequatur. Ab unde placeat obcaecati sapiente vero. Tenetur fugit totam mollitia molestiae est iusto facilis perspiciatis id, illo rem eum. Reiciendis laborum eum atque repudiandae autem dolores perferendis quaerat in ad vero ut, iste dolorem consequatur quisquam nobis ducimus iusto ex magni, laboriosam fuga sint deleniti minus enim? Cupiditate error quaerat eum voluptate eaque ipsum dolorum soluta qui nostrum numquam doloribus amet nemo ipsam nisi fuga, dolor obcaecati quae deserunt? Corrupti sequi quam, sunt nisi praesentium modi ut. Laudantium ad labore dicta corrupti voluptatem! Maxime, minima dolorum. Et quo, ex neque dolore harum perferendis eius quia modi inventore libero, ducimus adipisci laudantium dolores molestias repudiandae! Vel laboriosam deserunt explicabo quos nisi impedit similique laborum veritatis perferendis, reiciendis incidunt odio illo voluptatem est numquam ab adipisci hic nam? Sunt expedita necessitatibus labore blanditiis quasi
					eligendi nostrum debitis id perferendis porro atque eius, possimus, tempore nobis officiis? Similique officiis nesciunt vitae eum, minus reprehenderit modi laudantium eos unde mollitia odio ipsa totam perspiciatis eaque ea. Perferendis, praesentium omnis eligendi id cupiditate saepe suscipit ea sapiente consequatur vero harum quasi eius, rerum dolor nobis magni et! Nulla mollitia ullam, repellat, laboriosam beatae, possimus aspernatur quia ipsum asperiores officiis sint. Beatae veniam ut, expedita sapiente dignissimos eius quae vero quibusdam corporis quaerat excepturi voluptatum deserunt iste voluptate.
				</p>
			</Fragment>
		)
	}
}
export default Youtube
